version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=omnidb
      - DB_USER=omniuser
      - DB_PASS=passme123
    depends_on:
      - db

  db:
    image: postgres:14-alpine3.16
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=omnidb
      - POSTGRES_USER=omniuser
      - POSTGRES_PASSWORD=passme123

volumes:
  dev-db-data:
