# Generated by Django 4.1 on 2022-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_url', models.URLField(max_length=100, unique=True)),
                ('url_key', models.CharField(help_text='key to the long url', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='longurl',
            index=models.Index(fields=['url_key'], name='url_key_index'),
        ),
    ]
