# Generated by Django 4.1 on 2022-08-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longurl',
            name='short_url',
            field=models.URLField(unique=True),
        ),
    ]
