# Generated by Django 4.1 on 2022-08-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_longurl_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longurl',
            name='short_url',
        ),
    ]
