# Generated by Django 4.1 on 2022-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_remove_longurl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longurl',
            name='url_key',
            field=models.CharField(help_text='key to the long url', max_length=8, unique=True),
        ),
    ]
